name: "blob-ci"

on:
  workflow_dispatch:
    inputs:
      module:
        description: "Go module path to test"
        required: false
        type: string
        default: "pkg/component/blob"
  push:
    branches:
      - "feat**"
      - "fix**"
      - "hotfix**"
      - "chore**"
      - "main"
    paths:
      - "pkg/component/blob/**.go"
      - "pkg/component/blob/go.mod"
      - "pkg/component/blob/go.sum"
  pull_request:
    types:
      - opened
      - synchronize
      - reopened
    branches:
      - main
    paths:
      - "pkg/component/blob/**.go"
      - "pkg/component/blob/go.mod"
      - "pkg/component/blob/go.sum"

jobs:
  ci:
    uses: ./.github/workflows/common-ci.yml
    secrets: inherit
    with:
      module: "pkg/component/blob"
